export const PLAN_LIST  = '计划清单'
export const DEFINED_LIST  = '自定义清单'
export const TODAY      = '今日'
export const TOMORROW   = '明日'
export const WEEK       = '一周'
export const FUTURE     = '未来'
export const CUSTOM     = '固定习惯'
export const DONE       = '已完成'

export const TODO_LIST  = '待办列表'
export const CONTENT_TO_ADD = '要添加的内容'
export const EMPTY_CONFIRM = '列表内的清单将被清空，确定要清空此列表吗？'
export const CLOSE_LIST = '关闭列表'
export const LIST_TO_ADD = '要添加的列表'
export const ADD        = '添加'
export const EMPTY      = '清空'
export const SAVE       = '保存'
export const EDIT       = '编辑'
export const COMPLETE   = '完成'
export const CANCEL     = '取消'
export const TIP        = '提示'
export const TURN_ON    = '打开'
export const TURN_OFF   = '关闭'
export const COPY_TO    = '复制到'
export const MOVE_TO    = '移动到'
export const DONE_CLEAN_FAIL = '已完成列表清理失败'
export const DONE_CLEAN_END = '已完成列表清理完成'


export const CHOOSE     = '请选择'
export const LANG       = '语言'
export const LANG_CHN   = '简体中文'
export const LANG_EN    = 'English'