export const TODAY      = '今日'
export const TOMORROW   = '明日'
export const WEEK       = '一周'
export const FUTURE     = '未来'
export const CUSTOM     = '固定习惯'
export const DONE       = '已完成'

export const TODO_LIST  = '待办列表'
export const CONTENT_TO_ADD = '要添加的内容'
export const ADD        = '添加'
export const CLOSE_LIST = '关闭列表'
export const LIST_TO_ADD = '要添加的列表'
export const EMPTY      = '清空'
export const SAVE       = '保存'
export const EDIT       = '编辑'
export const EMPTY_CONFIRM = '列表内的清单将被清空，确定要清空此列表吗？'